version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fastapi
      - django

  django:
    build:
      context: .
      dockerfile: Dockerfile.django
    expose:
      - "8000"

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    expose:
      - "8000"